services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIN_DIR: bin
    ports:
      - "8800:8800"
    environment:
      - GOPHOTO_DSN=postgres://gophoto:password@db:5432?sslmode=disable
      - GOPHOTO_REDIS_ADDR=redis:6379
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./assets:/app/assets
      - ./templates:/app/templates
      - file_data:/app/uploads
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=gophoto
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gophoto
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gophoto"]
      interval: 1s
      timeout: 5s
      retries: 10
  redis:
    image: redis:latest
volumes:
  db_data:
  file_data: