DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS photo_metadata;
DROP TYPE IF EXISTS photo_variant;
DROP TABLE IF EXISTS album_photos CASCADE;
DROP TABLE IF EXISTS photos CASCADE;
DROP TYPE IF EXISTS photo_status;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS users;
