CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL, 
    email VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(250) NOT NULL,
    profile_picture_id INT,
    created_at TIMESTAMPTZ NOT NULL NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);

CREATE TYPE photo_status AS ENUM (
  'processing',
  'processed',
  'errored'
);

CREATE TABLE photos (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    key VARCHAR(250) NOT NULL,
    status photo_status NOT NULL DEFAULT 'processing',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_photos_user_id ON photos(user_id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_profile_picture_id
    FOREIGN KEY (profile_picture_id) REFERENCES photos(id) ON DELETE SET NULL;

CREATE TABLE albums (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_albums_user_id ON albums(user_id);

CREATE TABLE album_photos (
    album_id INT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
    photo_id INT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    UNIQUE(album_id, photo_id)
);

CREATE INDEX idx_album_photos_album_id ON album_photos(album_id);
CREATE INDEX idx_album_photos_photo_id ON album_photos(photo_id);

CREATE TYPE photo_variant AS ENUM ('original', 'large', 'small', 'medium', 'thumb', 'avatar');

CREATE TABLE photo_metadata (
    id SERIAL PRIMARY KEY,
    photo_id INT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    variant photo_variant NOT NULL,
    file_size BIGINT,
    mime_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(photo_id, variant)
);

CREATE INDEX idx_photo_metadata_photo_id ON photo_metadata(photo_id);

-- Sessions table for storing session data generated by github.com/alexedwards/scs/v2
CREATE TABLE sessions (
    token TEXT PRIMARY KEY,
    data BYTEA NOT NULL,
    expiry TIMESTAMPTZ NOT NULL
);

CREATE INDEX sessions_expiry_idx ON sessions (expiry);
