// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Album struct {
	ID        int32
	UserID    int32
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Photo struct {
	ID              int32
	AlbumID         sql.NullInt32
	Key             string
	Status          string
	DeleteableAfter sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID                int32
	FirstName         string
	LastName          string
	Email             string
	PasswordHash      string
	ProfilePictureKey sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
