// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"
	"time"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
  user_id,
  key,
  status
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, user_id, key, status, created_at, updated_at
`

type CreatePhotoParams struct {
	UserID int32
	Key    string
	Status PhotoStatus
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto, arg.UserID, arg.Key, arg.Status)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos
WHERE id = $1
`

func (q *Queries) DeletePhoto(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePhoto, id)
	return err
}

const getOrphanedPhotos = `-- name: GetOrphanedPhotos :many
SELECT id, user_id, key, status, created_at, updated_at FROM photos p
WHERE p.id NOT IN (
  SELECT ap.photo_id 
  FROM album_photos ap
)
AND p.id NOT IN (
  SELECT u.profile_picture_id 
  FROM users u 
  WHERE u.profile_picture_id IS NOT NULL
)
LIMIT 10
`

func (q *Queries) GetOrphanedPhotos(ctx context.Context) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, getOrphanedPhotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, user_id, key, status, created_at, updated_at
FROM photos
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetPhoto(ctx context.Context, id int32) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhotoStatus = `-- name: UpdatePhotoStatus :exec
UPDATE photos
SET
  status = $2,
  updated_at = $3
WHERE id = $1
`

type UpdatePhotoStatusParams struct {
	ID        int32
	Status    PhotoStatus
	UpdatedAt time.Time
}

func (q *Queries) UpdatePhotoStatus(ctx context.Context, arg UpdatePhotoStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePhotoStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
