// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_photos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addPhotoToAlbum = `-- name: AddPhotoToAlbum :one
INSERT INTO album_photos (album_id, photo_id)
VALUES ($1, $2)
RETURNING id, album_id, photo_id
`

type AddPhotoToAlbumParams struct {
	AlbumID int32
	PhotoID int32
}

func (q *Queries) AddPhotoToAlbum(ctx context.Context, arg AddPhotoToAlbumParams) (AlbumPhoto, error) {
	row := q.db.QueryRowContext(ctx, addPhotoToAlbum, arg.AlbumID, arg.PhotoID)
	var i AlbumPhoto
	err := row.Scan(&i.ID, &i.AlbumID, &i.PhotoID)
	return i, err
}

const deleteAlbumPhoto = `-- name: DeleteAlbumPhoto :exec
DELETE FROM album_photos
WHERE album_id = $1 AND photo_id = $2
`

type DeleteAlbumPhotoParams struct {
	AlbumID int32
	PhotoID int32
}

func (q *Queries) DeleteAlbumPhoto(ctx context.Context, arg DeleteAlbumPhotoParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumPhoto, arg.AlbumID, arg.PhotoID)
	return err
}

const getAlbumPhoto = `-- name: GetAlbumPhoto :one
SELECT p.id, p.user_id, p.key, p.status, p.created_at, p.updated_at, ap.album_id
FROM photos p
JOIN album_photos ap ON ap.photo_id = p.id
WHERE p.id = $1 LIMIT 1
`

type GetAlbumPhotoRow struct {
	ID        int32
	UserID    sql.NullInt32
	Key       string
	Status    PhotoStatus
	CreatedAt time.Time
	UpdatedAt time.Time
	AlbumID   int32
}

func (q *Queries) GetAlbumPhoto(ctx context.Context, id int32) (GetAlbumPhotoRow, error) {
	row := q.db.QueryRowContext(ctx, getAlbumPhoto, id)
	var i GetAlbumPhotoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AlbumID,
	)
	return i, err
}

const listPhotosByAlbum = `-- name: ListPhotosByAlbum :many
SELECT p.id, p.user_id, p.key, p.status, p.created_at, p.updated_at
FROM photos p
JOIN album_photos ap ON ap.photo_id = p.id
WHERE ap.album_id = $1
LIMIT $2
OFFSET $3
`

type ListPhotosByAlbumParams struct {
	AlbumID int32
	Limit   int32
	Offset  int32
}

func (q *Queries) ListPhotosByAlbum(ctx context.Context, arg ListPhotosByAlbumParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotosByAlbum, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
