// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (
  user_id, title
) VALUES (
  $1, $2
)
RETURNING id, user_id, title, cover_photo_id, num_photos, created_at, updated_at
`

type CreateAlbumParams struct {
	UserID int32
	Title  string
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, createAlbum, arg.UserID, arg.Title)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CoverPhotoID,
		&i.NumPhotos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementAlbumPhotoCount = `-- name: DecrementAlbumPhotoCount :exec
UPDATE albums
SET 
  num_photos = GREATEST(num_photos - 1, 0),
  updated_at = $2
WHERE id = $1
`

type DecrementAlbumPhotoCountParams struct {
	ID        int32
	UpdatedAt time.Time
}

func (q *Queries) DecrementAlbumPhotoCount(ctx context.Context, arg DecrementAlbumPhotoCountParams) error {
	_, err := q.db.ExecContext(ctx, decrementAlbumPhotoCount, arg.ID, arg.UpdatedAt)
	return err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAlbum, id)
	return err
}

const getAlbumById = `-- name: GetAlbumById :one
SELECT 
  a.id, a.user_id, a.title, a.cover_photo_id, a.num_photos, a.created_at, a.updated_at, 
  (SELECT COUNT(*) FROM album_photos WHERE album_id = a.id) AS num_photos
FROM albums a
WHERE a.id = $1
`

type GetAlbumByIdRow struct {
	ID           int32
	UserID       int32
	Title        string
	CoverPhotoID sql.NullInt32
	NumPhotos    int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	NumPhotos_2  int64
}

func (q *Queries) GetAlbumById(ctx context.Context, id int32) (GetAlbumByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAlbumById, id)
	var i GetAlbumByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CoverPhotoID,
		&i.NumPhotos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NumPhotos_2,
	)
	return i, err
}

const incrementAlbumPhotoCount = `-- name: IncrementAlbumPhotoCount :exec
UPDATE albums
SET 
  num_photos = num_photos + 1,
  updated_at = $2
WHERE id = $1
`

type IncrementAlbumPhotoCountParams struct {
	ID        int32
	UpdatedAt time.Time
}

func (q *Queries) IncrementAlbumPhotoCount(ctx context.Context, arg IncrementAlbumPhotoCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementAlbumPhotoCount, arg.ID, arg.UpdatedAt)
	return err
}

const listAlbumPhotoViewRows = `-- name: ListAlbumPhotoViewRows :many
WITH page_photos AS (
  SELECT p.id, p.key, p.created_at
  FROM photos p
  JOIN album_photos ap ON ap.photo_id = p.id
  WHERE ap.album_id = $1
  ORDER BY p.created_at DESC, p.id DESC
  LIMIT $2
  OFFSET $3
)
SELECT
  pp.id AS photo_id,
  pp.key AS photo_key,
  pm.variant,
  pm.width,
  pm.height,
  pm.mime_type
FROM page_photos pp
LEFT JOIN photo_metadata pm ON pm.photo_id = pp.id
ORDER BY
  pp.created_at DESC,
  pp.id DESC
`

type ListAlbumPhotoViewRowsParams struct {
	AlbumID int32
	Limit   int32
	Offset  int32
}

type ListAlbumPhotoViewRowsRow struct {
	PhotoID  int32
	PhotoKey string
	Variant  NullPhotoVariant
	Width    sql.NullInt32
	Height   sql.NullInt32
	MimeType sql.NullString
}

func (q *Queries) ListAlbumPhotoViewRows(ctx context.Context, arg ListAlbumPhotoViewRowsParams) ([]ListAlbumPhotoViewRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumPhotoViewRows, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumPhotoViewRowsRow
	for rows.Next() {
		var i ListAlbumPhotoViewRowsRow
		if err := rows.Scan(
			&i.PhotoID,
			&i.PhotoKey,
			&i.Variant,
			&i.Width,
			&i.Height,
			&i.MimeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByUser = `-- name: ListAlbumsByUser :many
SELECT                      
  a.id, 
  a.user_id,
  a.title,
  a.num_photos,
  a.created_at,
  a.updated_at,
  p_cover.id AS cover_photo_id,
  p_cover.key AS cover_photo_key
FROM albums a
LEFT JOIN photos p_cover ON p_cover.id = (
  SELECT photo_id 
  FROM album_photos 
  WHERE id = a.cover_photo_id 
  LIMIT 1
)
WHERE a.user_id = $1
GROUP BY 
  a.id, 
  a.user_id, 
  a.title, 
  a.created_at, 
  a.updated_at,
  p_cover.id, 
  p_cover.key
LIMIT $2
OFFSET $3
`

type ListAlbumsByUserParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

type ListAlbumsByUserRow struct {
	ID            int32
	UserID        int32
	Title         string
	NumPhotos     int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CoverPhotoID  sql.NullInt32
	CoverPhotoKey sql.NullString
}

func (q *Queries) ListAlbumsByUser(ctx context.Context, arg ListAlbumsByUserParams) ([]ListAlbumsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByUserRow
	for rows.Next() {
		var i ListAlbumsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.NumPhotos,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoverPhotoID,
			&i.CoverPhotoKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
  SET user_id = $2,
  title = $3,
  cover_photo_id = $4,
  updated_at = $5
WHERE id = $1
RETURNING id, user_id, title, cover_photo_id, num_photos, created_at, updated_at
`

type UpdateAlbumParams struct {
	ID           int32
	UserID       int32
	Title        string
	CoverPhotoID sql.NullInt32
	UpdatedAt    time.Time
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, updateAlbum,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.CoverPhotoID,
		arg.UpdatedAt,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CoverPhotoID,
		&i.NumPhotos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
