// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PhotoStatus string

const (
	PhotoStatusProcessing PhotoStatus = "processing"
	PhotoStatusProcessed  PhotoStatus = "processed"
	PhotoStatusErrored    PhotoStatus = "errored"
)

func (e *PhotoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotoStatus(s)
	case string:
		*e = PhotoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotoStatus: %T", src)
	}
	return nil
}

type NullPhotoStatus struct {
	PhotoStatus PhotoStatus
	Valid       bool // Valid is true if PhotoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PhotoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotoStatus), nil
}

type PhotoVariant string

const (
	PhotoVariantOriginal PhotoVariant = "original"
	PhotoVariantLarge    PhotoVariant = "large"
	PhotoVariantSmall    PhotoVariant = "small"
	PhotoVariantMedium   PhotoVariant = "medium"
	PhotoVariantThumb    PhotoVariant = "thumb"
	PhotoVariantAvatar   PhotoVariant = "avatar"
)

func (e *PhotoVariant) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotoVariant(s)
	case string:
		*e = PhotoVariant(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotoVariant: %T", src)
	}
	return nil
}

type NullPhotoVariant struct {
	PhotoVariant PhotoVariant
	Valid        bool // Valid is true if PhotoVariant is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotoVariant) Scan(value interface{}) error {
	if value == nil {
		ns.PhotoVariant, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotoVariant.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotoVariant) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotoVariant), nil
}

type Album struct {
	ID           int32
	UserID       int32
	Title        string
	CoverPhotoID sql.NullInt32
	NumPhotos    int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AlbumPhoto struct {
	ID        int32
	AlbumID   int32
	PhotoID   int32
	CreatedAt time.Time
}

type Photo struct {
	ID        int32
	UserID    sql.NullInt32
	Key       string
	Status    PhotoStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PhotoMetadatum struct {
	ID        int32
	PhotoID   int32
	Variant   PhotoVariant
	Width     int32
	Height    int32
	FileSize  int64
	MimeType  string
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID               int32
	FirstName        string
	LastName         string
	Email            string
	PasswordHash     string
	ProfilePictureID sql.NullInt32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
