// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_metadata.sql

package db

import (
	"context"
	"database/sql"
)

const createPhotoMetadata = `-- name: CreatePhotoMetadata :one
INSERT INTO photo_metadata (
  photo_id,
  variant,
  width,
  height,
  file_size,
  mime_type
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, photo_id, variant, width, height, file_size, mime_type, created_at
`

type CreatePhotoMetadataParams struct {
	PhotoID  int32
	Variant  PhotoVariant
	Width    int32
	Height   int32
	FileSize sql.NullInt64
	MimeType string
}

func (q *Queries) CreatePhotoMetadata(ctx context.Context, arg CreatePhotoMetadataParams) (PhotoMetadatum, error) {
	row := q.db.QueryRowContext(ctx, createPhotoMetadata,
		arg.PhotoID,
		arg.Variant,
		arg.Width,
		arg.Height,
		arg.FileSize,
		arg.MimeType,
	)
	var i PhotoMetadatum
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Variant,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const getPhotoMetadataByPhotoID = `-- name: GetPhotoMetadataByPhotoID :many
SELECT id, photo_id, variant, width, height, file_size, mime_type, created_at FROM photo_metadata
WHERE photo_id = $1
`

func (q *Queries) GetPhotoMetadataByPhotoID(ctx context.Context, photoID int32) ([]PhotoMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, getPhotoMetadataByPhotoID, photoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoMetadatum
	for rows.Next() {
		var i PhotoMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.Variant,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotoMetadataByPhotoIDAndVariant = `-- name: GetPhotoMetadataByPhotoIDAndVariant :one
SELECT id, photo_id, variant, width, height, file_size, mime_type, created_at FROM photo_metadata
where photo_id = $1 AND variant = $2
`

type GetPhotoMetadataByPhotoIDAndVariantParams struct {
	PhotoID int32
	Variant PhotoVariant
}

func (q *Queries) GetPhotoMetadataByPhotoIDAndVariant(ctx context.Context, arg GetPhotoMetadataByPhotoIDAndVariantParams) (PhotoMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getPhotoMetadataByPhotoIDAndVariant, arg.PhotoID, arg.Variant)
	var i PhotoMetadatum
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Variant,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}
