// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  first_name, last_name, email, password_hash
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, first_name, last_name, email, password_hash, profile_picture_id, created_at, updated_at
`

type CreateUserParams struct {
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password_hash, profile_picture_id, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT u.id, u.first_name, u.last_name, u.email, u.password_hash, u.profile_picture_id, u.created_at, u.updated_at, p.key AS profile_picture_key 
FROM users u
LEFT JOIN photos p ON u.profile_picture_id = p.id
WHERE u.id = $1
LIMIT 1
`

type GetUserByIdRow struct {
	ID                int32
	FirstName         string
	LastName          string
	Email             string
	PasswordHash      string
	ProfilePictureID  sql.NullInt32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProfilePictureKey sql.NullString
}

func (q *Queries) GetUserById(ctx context.Context, id int32) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfilePictureKey,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
  first_name = $2,
  last_name = $3,
  email = $4,
  password_hash = $5,
  profile_picture_id = $6,
  updated_at = $7
WHERE id = $1
RETURNING id, first_name, last_name, email, password_hash, profile_picture_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID               int32
	FirstName        string
	LastName         string
	Email            string
	PasswordHash     string
	ProfilePictureID sql.NullInt32
	UpdatedAt        time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.ProfilePictureID,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePictureID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
